services:
  db:
    build: ./mbms_db
    volumes:      
      - postgres_data:/var/lib/postgresql/data      
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  tomcat:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_DATABASE_HOST=${SQL_DATABASE_HOST}

volumes:
  postgres_data: