version: '2.0'
services:
  tomcat:
    build: .
    ports:
      - 1338:8080
    environment:
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_DATABASE_HOST=${SQL_DATABASE_HOST}
